# Ghana

Relevant sources of household-level micro records for Ghana are the **6 rounds of Ghana Living Standards Surveys** in particular:

- 1998/1999 **GLSS4** (EAs were first stratified into 3 ecological zones (Coastal, Forest, Savannah), and then within each zone further stratification was done into rural or urban areas)
- 2005/2006 **GLSS5** (EAs were first stratified into 10 administrative regions; within each region EAs were further sub-divided into rural or urban areas; EAs were also classified into  ecological zones and inclusion of Accra (GAMA) so that the survey results may be presented across 1) Coastal, 2) Forest, and 3) Northern Savannah, and 4) Accra).
- 2012/2013 **GLSS6** (EAs were allocated into 10 regions using probability proportional to population size (PPS), then further divided into urban and rural localities).

In contrast to the latest 2 waves GLSS4 is only representative for 3 (ecology) x 2 (rural/urban) zones.

GLSS collect information on the demographic characteristics of the population, their education, health, employment and time use, migration, housing conditions and household agriculture, with a specific focus on **labour force**, with a labour force module expanded in GLSS6 to include a section on child labour.

```{r gha-samples}

tmp <- data.frame(
  Survey=c("GLSS4", "GLSS5", "GLSS6"),
  Year=c("1997/98", "2005/06", "2012/13"),
  Regions=c(10, 10, 10),
  Districts=c(102, 110, 170),
  `Sample`=c(5998, 8687, 16772),
  `Urban`=c(2199, 3618, 7445),
  `Rural`=c(3799, 5069, 9327))

kable(tmp,
  justify="ccrrrrrrrr", format.args=list(big.mark=","),
  caption="Composition of GLSS Survey Samples")

```
